Add suffix appending function

diff --git a/pomfload b/pomfload
--- a/pomfload
+++ b/pomfload
@@ -3,12 +3,14 @@
 
 print_help_exit() {
 cat <<EOF
-Usage: $(basename "$0") [-u|-f|-p] [-s SITE]... FILE...
+Usage: $(basename "$0") [-u|-f|-p] [-t|-S SUFFIX] [-s SITE]... FILE...
 
 Options:
   -s SITE           Specify the site name to upload, can be used
                     multiple times to upload to multiple sites
                     (default sites: comfy.moe)
+  -S SUFFIX         Append SUFFIX to filenames before upload
+  -t                Upload as text files (equivalent to -S txt)
   -u                Output URL
   -f                Output filename only
   -p                Output the same way as the server responses
@@ -24,7 +26,7 @@ EOF
 }
 
 print_usage_exit() {
-    echo "Usage: $(basename "$0") [-u|-f|-p] [-s SITE]... FILE..."
+    echo "Usage: $(basename "$0") [-u|-f|-p] [-t|-S SUFFIX] [-s SITE]... FILE..."
     exit 1
 }
 
@@ -104,9 +106,9 @@ EOF
 # Save default sites names in newline-separated jq strings, which preserve whitespace
 DEFAULT_SITES="$(echo "${SITES_JSON}" | jq -c '.default|if type=="array" then .[] else . end')"
 SITES_COUNT=0
-OUTPUT_TYPE="url"
+OUTPUT_TYPE='url'
 
-while getopts ':hs:ufp' x; do
+while getopts ':hs:tS:ufp' x; do
     case $x in
         h)
             print_help_exit
@@ -121,6 +123,12 @@ while getopts ':hs:ufp' x; do
             # shifting forces subsequent getopts calls to skip already handled parameters
             shift $((OPTIND-1))    # Parse from the beginning of the *shifted* array
             OPTIND=1    # As you remember, bash and posh do not reset OPTIND automatically
+            ;;
+        t)
+            SUFFIX='txt'
+            ;;
+        S)
+            SUFFIX="${OPTARG}"
             ;;
         u)
             OUTPUT_TYPE='url'
@@ -157,12 +165,32 @@ done <<EOF
 EOF
 
 SITES_DATA="$(get_sites_data "${SITES_COUNT}" "$@")"
+
+# Remove sites names from "$@", only filenames are allowed to be there
 TO_SHIFT=$#
 for arg; do
     [ $# -eq $((TO_SHIFT + (TO_SHIFT - SITES_COUNT))) ] && break
     set -- "$@" "${arg}"
 done
 shift $((TO_SHIFT))
+
+
+if [ -n "${SUFFIX}" ]; then
+    TEMPDIR="$(mktemp --directory)"
+    [ -d "${TEMPDIR}" ] || (echo "Couldn't create a temporary directory" >&2 && exit 1)
+
+    TO_SHIFT=$#
+    for filename in "$@"; do
+        new_filename="${filename}.${SUFFIX}"
+        ln -s "${PWD}/${filename}" "${TEMPDIR}/${new_filename}"
+        set -- "$@" "${new_filename}"
+    done
+    shift $((TO_SHIFT))
+
+    # Server doesn't need to know the exact locations of our temporary symlinks
+    cd "${TEMPDIR}" || (echo "Failed to cd to ${TEMPDIR}" >&2 && exit 1)
+fi
+
 
 build_response_handler() {
     _SITE_DATA_="$1"
@@ -224,6 +252,7 @@ upload_print() {
     done
 }
 
+
 echo "${SITES_DATA}" | jq -c . | while read -r line; do
     MULTIPLE_FILES="$(get_field_value "${line}" multiple_files 'true')"
 
@@ -235,3 +264,6 @@ echo "${SITES_DATA}" | jq -c . | while read -r line; do
         done
     fi
 done
+
+# Cleanup
+[ -n "${TEMPDIR}" ] && cd "${OLDPWD}" && rm -r "${TEMPDIR}"
